# SPDX-License-Identifier: MPL-2.0
repos:
  - repo: local
    hooks:
      - id: add-spdx-headers
        name: Add SPDX headers
        entry: python scripts/insert_spdx_header.py
        language: system
        types: [text]
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: ["types-PyYAML"]
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.17.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
