# SPDX-License-Identifier: MPL-2.0
version: "3.9"

services:
  docs:
    image: python:3.11-slim
    command: bash -c "pip install --no-cache-dir mkdocs mkdocs-material && mkdocs serve -a 0.0.0.0:8000"
    working_dir: /workspace
    volumes:
      - ./:/workspace
    ports:
      - "8000:8000"
    environment:
      DOCS_ENV: development
      SITE_BASE_URL: http://localhost:8000
