# SPDX-License-Identifier: MPL-2.0
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r configs/python/requirements.txt
      - name: Run checks
        run: make check
      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./.coverage
  license_compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install license tooling
        run: |
          python -m pip install --upgrade pip
          pip install scancode-toolkit reuse
      - name: Run ScanCode license scan
        run: scancode --license --summary-licenses --json-pp scancode.json .
      - name: Verify REUSE compliance
        run: reuse lint
      - name: Upload license reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: license-compliance
          path: |
            scancode.json
